### PR TITLE
Add integrator, contrast and experiments for 'doubly' hypoelliptic models

### PR DESCRIPTION
**Pull request by matt-graham**
Opening this as a draft PR just to make it a bit easier to view the changes and add comments

### CODE REVIEW

**Comment by matt-graham** [comment]
This all looks good to me @YugaIgu. As far as I can tell the new transition densities / contrasts and integrator all correspond to what is written in the paper. I've added a few small clean-up commits to fix some linter (code style) warnings and added your name to the author list in the installation script. If you're happy with this we can merge this in to `main`.

**Comment by YugaIgu** [comment]
Thanks very much @matt-graham. I am happy with the new changes. 
In fact, I am developing a proposal integrator and its density for SMC to do Expectation Maximisation. 
Do you think I should add these developments as well into this branch? (or after merging dev_hypo into main, then create a new branch?)

**Comment by matt-graham** [comment]
> Do you think I should add these developments as well into this branch? (or after merging dev_hypo into main, then create a new branch?)

Either merging this then creating a new branch or continuing developing on this branch should be fine. I would probably lean slightly towards merging then creating a new branch to keep the changes more self-contained, but if you've got additional commits on your local `dev_hypo` already it may be easier to merge in the changes I made here and then continue on this branch.

**Comment by YugaIgu** [comment]
Thanks. I merged your pull-requests into main. I will create another branch for the next development relevant to EM.

**Pull request merged**
